[cursor]
style = "Underline"

[font]
size = 9.0
normal.family = "Liberation Mono"

# Default colors
[colors.primary]
background = '#161616'
foreground = '#f2f4f8'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#ee5396'
green   = '#25be6a'
yellow  = '#08bdba'
blue    = '#78a9ff'
magenta = '#be95ff'
cyan    = '#33b1ff'
white   = '#dfdfe0'

# Bright colors
[colors.bright]
black   = '#484848'
red     = '#f16da6'
green   = '#46c880'
yellow  = '#2dc7c4'
blue    = '#8cb6ff'
magenta = '#c8a5ff'
cyan    = '#52bdff'
white   = '#e4e4e5'

## Default colors
#[colors.primary]
#background = '#000000'
#foreground = '#eaeaea'
#
## Normal colors
#[colors.normal]
#black   = '#000000'
#red     = '#d54e53'
#green   = '#b9ca4a'
#yellow  = '#e6c547'
#blue    = '#7aa6da'
#magenta = '#c397d8'
#cyan    = '#70c0ba'
#white   = '#424242'
#
## Bright colors
#[colors.bright]
#black   = '#666666'
#red     = '#ff3334'
#green   = '#9ec400'
#yellow  = '#e7c547'
#blue    = '#7aa6da'
#magenta = '#b77ee0'
#cyan    = '#54ced6'
#white   = '#2a2a2a'
