/home/etheroot/pers/mus/BCSutta-TheZeestBand.webm
/home/etheroot/pers/mus/0to8,madeinnline-classicalphonk,p.2.mp3
/home/etheroot/pers/mus/369-JustLookatYou.mp3
/home/etheroot/pers/mus/AbelKorzeniowski-DanceForMeWallis.mp3
/home/etheroot/pers/mus/Airways-RecklessTongue.mp3
/home/etheroot/pers/mus/AlecBenjamin-BoyInTheBubble.mp3
/home/etheroot/pers/mus/Alexander23,JeremyZucker-Nothing'stheSame.mp3
/home/etheroot/pers/mus/AlexandreDesplat,LondonSymphonyOrchestra-TheImitationGame.mp3
/home/etheroot/pers/mus/AlexandreDesplat,LondonSymphonyOrchestra-Enigma.mp3
/home/etheroot/pers/mus/AlexandreDesplat,LondonSymphonyOrchestra-FarewelltoChristopher.mp3
/home/etheroot/pers/mus/AlexandreDesplat,LondonSymphonyOrchestra-AlanTuring'sLegacy.mp3
/home/etheroot/pers/mus/DmitriShostakovich,AndréRieu,JohannStraussOrchestra-TheSecondWaltz,Op.99a.mp3
/home/etheroot/pers/mus/AndrewBird-AreYouSerious.mp3
/home/etheroot/pers/mus/AnuvJain-Baarishein.mp3
/home/etheroot/pers/mus/AnuvJain-AlagAasmaan.mp3
/home/etheroot/pers/mus/AnuvJain-Gul.mp3
/home/etheroot/pers/mus/ArcticMonkeys-505.mp3
/home/etheroot/pers/mus/HarryLightfoot,Audiomachine-IWillFindYou.mp3
/home/etheroot/pers/mus/StevePorter,Audiomachine-Empathy.mp3
/home/etheroot/pers/mus/bbno$,YungGravy-shiningonmyex.mp3
/home/etheroot/pers/mus/bbno$-edamame(feat.RichBrian).mp3
/home/etheroot/pers/mus/bbno$-iseelondoniseefrance.mp3
/home/etheroot/pers/mus/bbno$-robertpatekson.mp3
/home/etheroot/pers/mus/Bcalm,softy-timeswithyou.mp3
/home/etheroot/pers/mus/BeachWeather-Sex,Drugs,Etc..mp3
/home/etheroot/pers/mus/BenjaminMartins-EscapingTime.mp3
/home/etheroot/pers/mus/Betcha-SwimNaked.mp3
/home/etheroot/pers/mus/Betcha-July.mp3
/home/etheroot/pers/mus/blackbear,TinyMeatGang-shortkingsanthem.mp3
/home/etheroot/pers/mus/Bleachers-Rollercoaster.mp3
/home/etheroot/pers/mus/Bleachers-Don'tTakeTheMoney.mp3
/home/etheroot/pers/mus/BoBurnham-BezosI.mp3
/home/etheroot/pers/mus/BoBurnham-Shit.mp3
/home/etheroot/pers/mus/BoBurnham-1985.mp3
/home/etheroot/pers/mus/BoBurnham-MicrowavePopcorn.mp3
/home/etheroot/pers/mus/BONESUK-DirtyLittleAnimals(FromtheseriesArcaneLeagueofLegends).mp3
/home/etheroot/pers/mus/boygenius,JulienBaker,PhoebeBridgers,LucyDacus-NotStrongEnough.mp3
/home/etheroot/pers/mus/BrianCrain-SongforSienna.mp3
/home/etheroot/pers/mus/BrianCrain-AttheIvyGate.mp3
/home/etheroot/pers/mus/BTS-Blue&Grey.mp3
/home/etheroot/pers/mus/carwash-striptease.mp3
/home/etheroot/pers/mus/CemeterySun-Fly.mp3
/home/etheroot/pers/mus/CharlotteSands-Dress.mp3
/home/etheroot/pers/mus/CigarettesAfterSex-K..mp3
/home/etheroot/pers/mus/ClaireRosinkranz-Hotel.mp3
/home/etheroot/pers/mus/CodyKo,MattMiggz-Fiat.mp3
/home/etheroot/pers/mus/COIN-CrashMyCar.mp3
/home/etheroot/pers/mus/ConanGray-WishYouWereSober.mp3
/home/etheroot/pers/mus/ConanGray-Maniac.mp3
/home/etheroot/pers/mus/ConanGray-TheCutThatAlwaysBleeds.mp3
/home/etheroot/pers/mus/CraigArmstrong,CeciliaWeston-IfYouShouldFall.mp3
/home/etheroot/pers/mus/DannyGonzalez-I'mGonnaKillSantaClaus.mp3
/home/etheroot/pers/mus/DannyGonzalez,DrewGooden-WeAreNottheSamePerson.mp3
/home/etheroot/pers/mus/DannyGonzalez-Yummy.mp3
/home/etheroot/pers/mus/DannyGonzalez-MyDadIsRich.mp3
/home/etheroot/pers/mus/DannyGonzalez,KurtisConner-InLoveWithACreeper.mp3
/home/etheroot/pers/mus/DannyGonzalez-IGhostedKevinJonas.mp3
/home/etheroot/pers/mus/Dayglow-CanICallYouTonight.mp3
/home/etheroot/pers/mus/Dayglow-HotRod.mp3
/home/etheroot/pers/mus/DeadPoetSociety-AmericanBlood.mp3
/home/etheroot/pers/mus/Deafheaven-DreamHouse.mp3
/home/etheroot/pers/mus/Deafheaven-Irresistible.mp3
/home/etheroot/pers/mus/Deafheaven-Sunbather.mp3
/home/etheroot/pers/mus/Deafheaven-Vertigo.mp3
/home/etheroot/pers/mus/Deafheaven-Windows.mp3
/home/etheroot/pers/mus/Deafheaven-ThePecanTree.mp3
/home/etheroot/pers/mus/DesRocs-SuicideRomantics.mp3
/home/etheroot/pers/mus/DE'WAYNE-SIMPLE(feat.IDONTKNOWHOWBUTTHEYFOUNDME).mp3
/home/etheroot/pers/mus/dodie-HateMyself.mp3
/home/etheroot/pers/mus/dodie-GotWeird.mp3
/home/etheroot/pers/mus/DojaCat-Woman.mp3
/home/etheroot/pers/mus/DPRIAN-Mood.mp3
/home/etheroot/pers/mus/Dreamcatcher-BEcause.mp3
/home/etheroot/pers/mus/DVRST-CloseEyes.mp3
/home/etheroot/pers/mus/DVRST-CloseEyes-SpedUp.mp3
/home/etheroot/pers/mus/Eminem-Godzilla(feat.JuiceWRLD).mp3
/home/etheroot/pers/mus/ENHYPEN-Drunk-Dazed.mp3
/home/etheroot/pers/mus/EthelCain-Crush.mp3
/home/etheroot/pers/mus/EthelCain-AmericanTeenager.mp3
/home/etheroot/pers/mus/EzioBosso-Rain,inYourBlackEyes.mp3
/home/etheroot/pers/mus/DVRST-Slapper.mp3
/home/etheroot/pers/mus/FelixMendelssohn,MaximVengerov,KurtMasur,Gewandhausorchester-Mendelssohn-ViolinConcertoinEMinor,Op.64,MWVO14-I.Allegromoltoappassionato.mp3
/home/etheroot/pers/mus/Fink-LookingTooClosely.mp3
/home/etheroot/pers/mus/FINNEAS-Can'tWaitToBeDead.mp3
/home/etheroot/pers/mus/floracash-You'reSomebodyElse.mp3
/home/etheroot/pers/mus/Florence+TheMachine-CosmicLove.mp3
/home/etheroot/pers/mus/FlyByMidnight-LoveMeLikeaFriend.mp3
/home/etheroot/pers/mus/FORGOTTENAGE-EndoftheWorld.mp3
/home/etheroot/pers/mus/FrédéricChopin,ParkEunShik-NocturneNo.1inB-FlatMinor,Op.9No.1.mp3
/home/etheroot/pers/mus/FridayPilotsClub-EndofIt.mp3
/home/etheroot/pers/mus/FridayPilotsClub-HotMess.mp3
/home/etheroot/pers/mus/GeekMusic-DeathNote-L'sTheme-MainTheme.mp3
/home/etheroot/pers/mus/girli-MoreThanaFriend.mp3
/home/etheroot/pers/mus/GlassAnimals-TheOtherSideOfParadise.mp3
/home/etheroot/pers/mus/GlassAnimals-SpaceGhostCoastToCoast.mp3
/home/etheroot/pers/mus/HaddadiVonEngst-Run.mp3
/home/etheroot/pers/mus/Halestorm-IMisstheMisery.mp3
/home/etheroot/pers/mus/half•alive-stillfeel..mp3
/home/etheroot/pers/mus/half•alive-What'sWrong.mp3
/home/etheroot/pers/mus/half•alive-Summerland.mp3
/home/etheroot/pers/mus/half•alive-Nobody(feat.dodie).mp3
/home/etheroot/pers/mus/HansZimmer-Time.mp3
/home/etheroot/pers/mus/HansZimmer-CornfieldChase.mp3
/home/etheroot/pers/mus/HansZimmer-DayOne(InterstellarTheme).mp3
/home/etheroot/pers/mus/HansZimmer,JaviLobe-CornfieldChase-PianoVersion.mp3
/home/etheroot/pers/mus/HarryStyles-FineLine.mp3
/home/etheroot/pers/mus/HarryStyles-LittleFreak.mp3
/home/etheroot/pers/mus/HAUSER-RiverFlowsinYou.mp3
/home/etheroot/pers/mus/Hearts&Colors-Lion.mp3
/home/etheroot/pers/mus/HowardHarper-Barnes-TheEnglishAffair.mp3
/home/etheroot/pers/mus/IchikaNito-Isolation.mp3
/home/etheroot/pers/mus/IchikaNito-imissyou.mp3
/home/etheroot/pers/mus/IchikaNito-Homesick.mp3
/home/etheroot/pers/mus/IchikaNito-Qualm.mp3
/home/etheroot/pers/mus/IDONTKNOWHOWBUTTHEYFOUNDME-DoItAllTheTime.mp3
/home/etheroot/pers/mus/IDONTKNOWHOWBUTTHEYFOUNDME-SocialClimb.mp3
/home/etheroot/pers/mus/IDONTKNOWHOWBUTTHEYFOUNDME-BleedMagic.mp3
/home/etheroot/pers/mus/IDONTKNOWHOWBUTTHEYFOUNDME-Absinthe.mp3
/home/etheroot/pers/mus/IDONTKNOWHOWBUTTHEYFOUNDME-MadIQs.mp3
/home/etheroot/pers/mus/IDONTKNOWHOWBUTTHEYFOUNDME-NewInvention.mp3
/home/etheroot/pers/mus/IDONTKNOWHOWBUTTHEYFOUNDME-SugarPills.mp3
/home/etheroot/pers/mus/IDONTKNOWHOWBUTTHEYFOUNDME-KissGoodnight.mp3
/home/etheroot/pers/mus/IDONTKNOWHOWBUTTHEYFOUNDME-FromTheGallows.mp3
/home/etheroot/pers/mus/INNDRIVE-ShakeIt-Extended.mp3
/home/etheroot/pers/mus/IsaacDunbar-fanbehavior.mp3
/home/etheroot/pers/mus/IZONE-LaVieenRose.mp3
/home/etheroot/pers/mus/Jacob'sPiano-Mariaged'Amour.mp3
/home/etheroot/pers/mus/Jacob'sPiano-ArrivaloftheBirds.mp3
/home/etheroot/pers/mus/JacobYoffee-WithResolve.mp3
/home/etheroot/pers/mus/JaedenCamstra-Infomercials&HeavyEyelids.mp3
/home/etheroot/pers/mus/JaymesYoung-FeelSomething.mp3
/home/etheroot/pers/mus/JohannesBornlöf-Let'sRunAwayTogether.mp3
/home/etheroot/pers/mus/JohannesBornlöf-NocturnalWaltz.mp3
/home/etheroot/pers/mus/JohannSebastianBach,LangLang-GoldbergVariations,BWV988-Aria.mp3
/home/etheroot/pers/mus/JONY-Мирсошёлсума.mp3
/home/etheroot/pers/mus/JONY-Небесныерозы.mp3
/home/etheroot/pers/mus/JulienBaker,PhoebeBridgers,LucyDacus-Me&MyDog.mp3
/home/etheroot/pers/mus/KatyPerry-LastFridayNight(T.G.I.F.).mp3
/home/etheroot/pers/mus/KatyPerry-HarleysInHawaii.mp3
/home/etheroot/pers/mus/LanaDelRey-Cola.mp3
/home/etheroot/pers/mus/LanaDelRey-PrettyWhenYouCry.mp3
/home/etheroot/pers/mus/LanaDelRey-MoneyPowerGlory.mp3
/home/etheroot/pers/mus/LanaDelRey-FuckedMyWayUpToTheTop.mp3
/home/etheroot/pers/mus/LanaDelRey-FuckitIloveyou.mp3
/home/etheroot/pers/mus/Lorde-BuzzcutSeason.mp3
/home/etheroot/pers/mus/Lorde-Team.mp3
/home/etheroot/pers/mus/Lorde-MoodRing.mp3
/home/etheroot/pers/mus/LordHuron-MeetMeInTheWoods.mp3
/home/etheroot/pers/mus/Lovejoy-CallMeWhatYouLike.mp3
/home/etheroot/pers/mus/lovelytheband-broken.mp3
/home/etheroot/pers/mus/LudovicoEinaudi-NuvoleBianche.mp3
/home/etheroot/pers/mus/LudovicoEinaudi,RobertZiegler,RoyalPhilharmonicOrchestra-Divenire.mp3
/home/etheroot/pers/mus/LudovicoEinaudi,RobertZiegler,RoyalPhilharmonicOrchestra-Primavera.mp3
/home/etheroot/pers/mus/LudovicoEinaudi-Oltremare.mp3
/home/etheroot/pers/mus/LudovicoEinaudi,DanielHope,IVirtuosiItaliani-Experience.mp3
/home/etheroot/pers/mus/MAMAMOO-HIP.mp3
/home/etheroot/pers/mus/MarcoLuka-domewrong.mp3
/home/etheroot/pers/mus/MARINA-Froot.mp3
/home/etheroot/pers/mus/MarkJohnPetrie,AndrewJamesPrahlow,Audiomachine-LeapofFaith.mp3
/home/etheroot/pers/mus/MattMaeson-Cringe.mp3
/home/etheroot/pers/mus/MaxRichter,MariSamuelsen,KonzerthausorchesterBerlin,JonathanStockhammer-November.mp3
/home/etheroot/pers/mus/MenITrust-ShowMeHow.mp3
/home/etheroot/pers/mus/Meshuggah-Clockworks.mp3
/home/etheroot/pers/mus/Meshuggah-BorninDissonance.mp3
/home/etheroot/pers/mus/Meshuggah-Monstrocity.mp3
/home/etheroot/pers/mus/Meshuggah-BytheTon.mp3
/home/etheroot/pers/mus/Meshuggah-ViolentSleepofReason.mp3
/home/etheroot/pers/mus/Meshuggah-IvoryTower.mp3
/home/etheroot/pers/mus/Meshuggah-Stifled.mp3
/home/etheroot/pers/mus/Meshuggah-Nostrum.mp3
/home/etheroot/pers/mus/Meshuggah-OurRageWon'tDie.mp3
/home/etheroot/pers/mus/Meshuggah-IntoDecay.mp3
/home/etheroot/pers/mus/MiddleMilk,MoistCr1tikal-OneNippleataTime.mp3
/home/etheroot/pers/mus/MistaPlaya-ENEMYANDREVENGE.mp3
/home/etheroot/pers/mus/Mitraz-Junoon.mp3
/home/etheroot/pers/mus/Mitraz-Muskurahat.mp3
/home/etheroot/pers/mus/Mitraz-Akhiyaan.mp3
/home/etheroot/pers/mus/Mitraz-Alfaazo.mp3
/home/etheroot/pers/mus/MoisésNieto-MysteryofLoveVisionsofGideon(From'CallMebyYourName').mp3
/home/etheroot/pers/mus/mxnarch-Nightwing.mp3
/home/etheroot/pers/mus/MyChemicalRomance-FamousLastWords.mp3
/home/etheroot/pers/mus/MyChemicalRomance-NaNaNa(NaNaNaNaNaNaNaNaNa).mp3
/home/etheroot/pers/mus/NOEL-Crow.mp3
/home/etheroot/pers/mus/NOTD,shymartin-KeepYouMine.mp3
/home/etheroot/pers/mus/NOTD,AstridS-IDon'tKnowWhy.mp3
/home/etheroot/pers/mus/NothingButThieves-TripSwitch.mp3
/home/etheroot/pers/mus/NothingButThieves-HoneyWhiskey.mp3
/home/etheroot/pers/mus/NothingButThieves-YouKnowMeTooWell.mp3
/home/etheroot/pers/mus/NothingButThieves-IsEverybodyGoingCrazy.mp3
/home/etheroot/pers/mus/NothingButThieves-Phobia.mp3
/home/etheroot/pers/mus/NothingButThieves-CanYouAffordtoBeAnIndividual.mp3
/home/etheroot/pers/mus/NothingButThieves-Futureproof.mp3
/home/etheroot/pers/mus/NothingButThieves-IfIWereYou.mp3
/home/etheroot/pers/mus/NothingButThieves-MoralPanic.mp3
/home/etheroot/pers/mus/NovoAmor,Lowswimmer-Alps.mp3
/home/etheroot/pers/mus/OssieWoods-ReminiscenceOfInnocence.mp3
/home/etheroot/pers/mus/PalayeRoyale-Mr.DoctorMan.mp3
/home/etheroot/pers/mus/PalayeRoyale-LittleBastards.mp3
/home/etheroot/pers/mus/PatrickWatson-Jetelaisseraidesmots.mp3
/home/etheroot/pers/mus/PeterGundry-TheVampireMasquerade.mp3
/home/etheroot/pers/mus/PhoebeBridgers-Punisher.mp3
/home/etheroot/pers/mus/PhoebeBridgers-ChineseSatellite.mp3
/home/etheroot/pers/mus/PhoebeBridgers-MoonSong.mp3
/home/etheroot/pers/mus/PhoebeBridgers-IKnowTheEnd.mp3
/home/etheroot/pers/mus/PHOROMANE-FIGHTTOSHIT.mp3
/home/etheroot/pers/mus/PLVTINUM-COFFIN.mp3
/home/etheroot/pers/mus/PLVTINUM-STRESSMEOUT.mp3
/home/etheroot/pers/mus/Polyphia-87.mp3
/home/etheroot/pers/mus/Polyphia,AaronMarshall-SweetTea.mp3
/home/etheroot/pers/mus/Polyphia,NickJohnston-Champagne.mp3
/home/etheroot/pers/mus/Polyphia,JasonRichardson-Aviator.mp3
/home/etheroot/pers/mus/Polyphia,JakubZytecki-TheJungle.mp3
/home/etheroot/pers/mus/Polyphia-Memory.mp3
/home/etheroot/pers/mus/Polyphia-MoodSwing.mp3
/home/etheroot/pers/mus/Polyphia,NickSampson-Hourglass.mp3
/home/etheroot/pers/mus/Polyphia-JamesFranco.mp3
/home/etheroot/pers/mus/Polyphia,MarioCamarena,ErickHansel-Baditude.mp3
/home/etheroot/pers/mus/Polyphia-Finale.mp3
/home/etheroot/pers/mus/Pritam,ArijitSingh-Ilahi.mp3
/home/etheroot/pers/mus/PVRIS-DeadWeight.mp3
/home/etheroot/pers/mus/PVRIS-Monster.mp3
/home/etheroot/pers/mus/PyotrIlyichTchaikovsky,JosefSakonov,LondonFestivalOrchestra-Valsesentimentale,Op.51,No.6.mp3
/home/etheroot/pers/mus/RickyMontgomery-Cabo.mp3
/home/etheroot/pers/mus/RIOPY-ILoveYou.mp3
/home/etheroot/pers/mus/RIOPY-WydenDown.mp3
/home/etheroot/pers/mus/RobertoCacciapaglia-WildSide.mp3
/home/etheroot/pers/mus/Royal&theSerpent-overwhelmed.mp3
/home/etheroot/pers/mus/Royal&theSerpent-ican'tgethigh.mp3
/home/etheroot/pers/mus/Rynx-ClubPoor(withTinyMeatGang).mp3
/home/etheroot/pers/mus/SabrinaCarpenter-Why.mp3
/home/etheroot/pers/mus/SabrinaCarpenter-AlmostLove.mp3
/home/etheroot/pers/mus/SecessionStudios-TheUntold.mp3
/home/etheroot/pers/mus/SecessionStudios-Lucifer'sWaltz.mp3
/home/etheroot/pers/mus/SecessionStudios,GregDombrowski-QueenoftheDamned.mp3
/home/etheroot/pers/mus/SEVENTEEN-Rockwithyou.mp3
/home/etheroot/pers/mus/SmyangPiano-PiedPiper.mp3
/home/etheroot/pers/mus/SmyangPiano-Euphoria.mp3
/home/etheroot/pers/mus/SmyangPiano-TheTruthUntold.mp3
/home/etheroot/pers/mus/SmyangPiano-MagicShop.mp3
/home/etheroot/pers/mus/SmyangPiano-FakeLove.mp3
/home/etheroot/pers/mus/SmyangPiano,tamagopalette-Euphoria-LofiEdit.mp3
/home/etheroot/pers/mus/SmyangPiano,tamagopalette-Serendipity-LofiEdit.mp3
/home/etheroot/pers/mus/StoryUntold-gxxglemaps.mp3
/home/etheroot/pers/mus/StrayKids-CASE143.mp3
/home/etheroot/pers/mus/SufjanStevens-DeathwithDignity.mp3
/home/etheroot/pers/mus/SufjanStevens-FourthofJuly.mp3
/home/etheroot/pers/mus/SufjanStevens-JohnMyBeloved.mp3
/home/etheroot/pers/mus/SydneySprague,DanielleDurack-objectpermanence.mp3
/home/etheroot/pers/mus/TAEMIN-Criminal.mp3
/home/etheroot/pers/mus/TAEMIN-Advice.mp3
/home/etheroot/pers/mus/Tamer-BeautifulCrime.mp3
/home/etheroot/pers/mus/TaylorSwift-22.mp3
/home/etheroot/pers/mus/TaylorSwift-PaperRings.mp3
/home/etheroot/pers/mus/TaylorSwift-LondonBoy.mp3
/home/etheroot/pers/mus/TaylorSwift-goldrush.mp3
/home/etheroot/pers/mus/TaylorSwift-ivy.mp3
/home/etheroot/pers/mus/TaylorSwift-rightwhereyouleftme-bonustrack.mp3
/home/etheroot/pers/mus/TaylorSwift-NothingNew(feat.PhoebeBridgers)(Taylor’sVersion)(FromTheVault).mp3
/home/etheroot/pers/mus/TaylorSwift-You'reOnYourOwn,Kid.mp3
/home/etheroot/pers/mus/TaylorSwift-Paris.mp3
/home/etheroot/pers/mus/TessaViolet-Crush.mp3
/home/etheroot/pers/mus/The1975-SomebodyElse.mp3
/home/etheroot/pers/mus/The1975-BeMyMistake.mp3
/home/etheroot/pers/mus/TheAlgorithm-boot.mp3
/home/etheroot/pers/mus/TheAlgorithm-floatingpoint.mp3
/home/etheroot/pers/mus/TheAlgorithm-pointers.mp3
/home/etheroot/pers/mus/TheAlgorithm-bruteforce.mp3
/home/etheroot/pers/mus/TheAlgorithm-userspace.mp3
/home/etheroot/pers/mus/TheAlgorithm-shellcode.mp3
/home/etheroot/pers/mus/TheAlgorithm-hex.mp3
/home/etheroot/pers/mus/TheAlgorithm,Igorrr-deadlock.mp3
/home/etheroot/pers/mus/TheAlgorithm-rootkit.mp3
/home/etheroot/pers/mus/TheAlgorithm-trojans(hardmode).mp3
/home/etheroot/pers/mus/TheAlgorithm-idle.mp3
/home/etheroot/pers/mus/TheAlgorithm-overclock.mp3
/home/etheroot/pers/mus/TheAlgorithm-doubledataratesynchronousdynamicrandomaccessmemory.mp3
/home/etheroot/pers/mus/TheAlgorithm-floatingpoint-DrumcorpsRemix.mp3
/home/etheroot/pers/mus/TheAlgorithm-runtime.mp3
/home/etheroot/pers/mus/TheAlgorithm-sourcecode.mp3
/home/etheroot/pers/mus/TheAlgorithm-dynamicrecompilation.mp3
/home/etheroot/pers/mus/TheAlgorithm-userspace-VolkorXRemix.mp3
/home/etheroot/pers/mus/TheAlgorithm-floatingpoint-VaporwaveRemix.mp3
/home/etheroot/pers/mus/TheAlgorithm-rootkit-ChiptuneRemix.mp3
/home/etheroot/pers/mus/TheAlgorithm-SegmentationFault.mp3
/home/etheroot/pers/mus/TheAlgorithm-InterruptHandler.mp3
/home/etheroot/pers/mus/TheAlgorithm-Decompilation.mp3
/home/etheroot/pers/mus/TheAlgorithm-Readonly.mp3
/home/etheroot/pers/mus/TheAlgorithm-CryptographicMemory.mp3
/home/etheroot/pers/mus/TheAlgorithm-ObjectResurrection.mp3
/home/etheroot/pers/mus/TheAlgorithm-Multithreading.mp3
/home/etheroot/pers/mus/TheAlgorithm-OracleMachine.mp3
/home/etheroot/pers/mus/TheAlgorithm-DataRenaissance.mp3
/home/etheroot/pers/mus/TheAlgorithm-InlineAssembly.mp3
/home/etheroot/pers/mus/TheBandCAMINO-1LastCigarette.mp3
/home/etheroot/pers/mus/TheBlueStones-BeMyFire.mp3
/home/etheroot/pers/mus/TheHaunt-Cigarettes&Feelings.mp3
/home/etheroot/pers/mus/TheLocalTrain-ChooLo.mp3
/home/etheroot/pers/mus/TheLocalTrain-DilMere.mp3
/home/etheroot/pers/mus/TheNeighbourhood-Nervous.mp3
/home/etheroot/pers/mus/TheNextStep-Flying.mp3
/home/etheroot/pers/mus/TheOhHellos-HelloMyOldHeart.mp3
/home/etheroot/pers/mus/The Technicolors - Tonight You Are Mine.mp3
/home/etheroot/pers/mus/The Technicolors - Neon Roses.mp3
/home/etheroot/pers/mus/TheUnlikelyCandidates-Novocaine.mp3
/home/etheroot/pers/mus/Thexx-Intro.mp3
/home/etheroot/pers/mus/TinyMeatGang-NoFlex.mp3
/home/etheroot/pers/mus/TinyMeatGang-WalkMan.mp3
/home/etheroot/pers/mus/TinyMeatGang-BrokeBitch.mp3
/home/etheroot/pers/mus/TinyMeatGang-Sofia.mp3
/home/etheroot/pers/mus/TinyMeatGang-Daddy(feat.QuinnXCII).mp3
/home/etheroot/pers/mus/TomCardy-RedFlags(feat.Montaigne).mp3
/home/etheroot/pers/mus/TropicGold-Chemicals.mp3
/home/etheroot/pers/mus/TwentyOnePilots-NicoandtheNiners.mp3
/home/etheroot/pers/mus/TWINXL,DREAMERS-Upgrade.mp3
/home/etheroot/pers/mus/TwoFeet-IFeelLikeI'mDrowning.mp3
/home/etheroot/pers/mus/PhoebeBridgers-WaitingRoom.mp3
/home/etheroot/pers/mus/JulienBaker-BalladofBigNothing.mp3
/home/etheroot/pers/mus/AramKhachaturian,LondonSymphonyOrchestra,StanleyBlack-Masquerade-BalletSuite-1.Waltz.mp3
/home/etheroot/pers/mus/VÉRITÉ-SomebodyElse.mp3
/home/etheroot/pers/mus/Waterparks-StupidforYou.mp3
/home/etheroot/pers/mus/Waterparks-EasyToHate.mp3
/home/etheroot/pers/mus/Waterparks-HighDefinition.mp3
/home/etheroot/pers/mus/Waterparks-Numb.mp3
/home/etheroot/pers/mus/Waterparks-SnowGlobe.mp3
/home/etheroot/pers/mus/Waterparks-FUCKABOUTIT(feat.blackbear).mp3
/home/etheroot/pers/mus/Weathers-C'estlavie.mp3
/home/etheroot/pers/mus/WhyDon'tWe-CometoBrazil.mp3
/home/etheroot/pers/mus/WilburSoot-YourNewBoyfriend.mp3
/home/etheroot/pers/mus/WolfgangAmadeusMozart,ConcertoKöln,WernerEhrhardt-SixGermanDances,K.571-No.1inD.mp3
/home/etheroot/pers/mus/YONAKA-CallMeaSaint.mp3
/home/etheroot/pers/mus/YoungerHunger-DeadInside.mp3
/home/etheroot/pers/mus/YUNGBLUD-strawberrylipstick.mp3
/home/etheroot/pers/mus/YungGravy,bbno$-WhipATesla.mp3
/home/etheroot/pers/mus/YungGravy-oops!.mp3
/home/etheroot/pers/mus/YungGravy-yup!.mp3
/home/etheroot/pers/mus/YungGravy-DancingInTheRain.mp3
/home/etheroot/pers/mus/YungGravy-C’estLaVie(withbbno$&RichBrian).mp3
/home/etheroot/pers/mus/ZackHemsey-TheWay(Instrumental).mp3
/home/etheroot/pers/mus/Zaeden-sochanatha.mp3
/home/etheroot/pers/mus/Zaeden-kyakaroon.mp3
